// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdeWidu-NnIt-Qw2JEAyYSt9DD142uG24',
    appId: '1:501287658213:web:53d43bfbbd158e6629ea0c',
    messagingSenderId: '501287658213',
    projectId: 'flutter-chat-app-jw',
    authDomain: 'flutter-chat-app-jw.firebaseapp.com',
    storageBucket: 'flutter-chat-app-jw.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjieFs28gLs884UIU5VvWNsoBHBpkqw-s',
    appId: '1:501287658213:android:69f133057de015ad29ea0c',
    messagingSenderId: '501287658213',
    projectId: 'flutter-chat-app-jw',
    storageBucket: 'flutter-chat-app-jw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_o6mKvujvGARBxexrmIFRGM19_ZjuLI',
    appId: '1:501287658213:ios:04ca111d7afcbc8729ea0c',
    messagingSenderId: '501287658213',
    projectId: 'flutter-chat-app-jw',
    storageBucket: 'flutter-chat-app-jw.appspot.com',
    iosBundleId: 'com.example.chatApp031023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl_o6mKvujvGARBxexrmIFRGM19_ZjuLI',
    appId: '1:501287658213:ios:815a2f46893397bb29ea0c',
    messagingSenderId: '501287658213',
    projectId: 'flutter-chat-app-jw',
    storageBucket: 'flutter-chat-app-jw.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
